### PR TITLE
Updates to demo values for job title and company name

### PR DESCRIPTION
**Pull request by mobimation-gunnar**
AF Connect Once API adds parameters to specify
company name of prospective employer and
the job title to apply for.
The af-connect-demo is concerned with populating/rendering a form for demo purposes 
of CV data received upon user consent.

The demo is updated to make use of these
new parameters where access to global configuration comes from
import of a "af-connect-module" bundle, see  folder ```./app/public/vendor```

### CODE REVIEW

**Review by ixuz — CHANGES_REQUESTED** [review]
1. Delete the old bundle from this folder: https://github.com/MagnumOpuses/af-connect-demo/tree/forrr-new-params-consent/app/public/vendor
1. Make sure to import the new bundle from the correct folder, see highlighted line here: https://github.com/MagnumOpuses/af-connect-demo/blob/forrr-new-params-consent/app/views/pages/index.ejs#L83

**Comment by mobimation-gunnar** [comment]
Changes done.

**Review by ixuz — COMMENTED** [review]
Nice changes ! 👍

**Review by ixuz — APPROVED** [review]
Looks good.

**Comment by ixuz** [comment]
@mobimation-gunnar  may now "Squash and merge" this PR into `stage`.

**Pull request merged**
